var lista_cidades_redespacho = [
    {cidade: "ABATIA", uf: "PR", agencia: "SANTO ANTONIO DA PLATINA"},
    {cidade: "ABDON BATISTA", uf: "SC", agencia: "CAMPOS NOVOS"},
    {cidade: "ADRIANOPOLIS", uf: "PR", agencia: "COLOMBO"},
    {cidade: "AGUDOS DO SUL", uf: "PR", agencia: "CURITIBA"},
    {cidade: "ALFREDO WAGNER", uf: "SC", agencia: "RIO DO SUL"},
    {cidade: "ALTAMIRA DO PARANA", uf: "PR", agencia: "LARANJEIRAS DO SUL"},
    {cidade: "ALTO BELA VISTA", uf: "SC", agencia: "CONCORDIA"},
    {cidade: "ALTO PIRIQUI", uf: "PR", agencia: "LONDRINA"},
    {cidade: "ALVORADA DO SUL", uf: "PR", agencia: "LONDRINA"},
    {cidade: "AMAPORA", uf: "PR", agencia: "MARINGA"},
    {cidade: "AMARAL FERRADOR", uf: "RS", agencia: "CAMAQUA"},
    {cidade: "ANAHY", uf: "PR", agencia: "CASCAVEL AGENCIA"},
    {cidade: "ANDRE DA ROCHA", uf: "RS", agencia: "NOVA PRATA"},
    {cidade: "ANGULO", uf: "PR", agencia: "MARINGA"},
    {cidade: "ANITA GARIBALDI", uf: "SC", agencia: "LAGES"},
    {cidade: "ANITAPOLIS", uf: "SC", agencia: "SAO JOSE"},
    {cidade: "ANTONINA", uf: "PR", agencia: "CURITIBA"},
    {cidade: "ARAMBARE", uf: "RS", agencia: "CAMAQUA"},
    {cidade: "ARAPOTI", uf: "PR", agencia: "CASTRO"},
    {cidade: "ARROIO DO PADRE", uf: "RS", agencia: "PELOTAS"},
    {cidade: "ARROIO GRANDE", uf: "RS", agencia: "PELOTAS"},
    {cidade: "ARVOREDO", uf: "SC", agencia: "CHAPECO"},
    {cidade: "ASSAI", uf: "PR", agencia: "LONDRINA"},
    {cidade: "ATALAIA", uf: "PR", agencia: "LONDRINA"},
    {cidade: "AUREA", uf: "RS", agencia: "ERECHIM"},
    {cidade: "BALNEARIO ARROIO DO SILVA", uf: "SC", agencia: "ARARANGUA"},
    {cidade: "BALNEARIO GAIVOTA", uf: "SC", agencia: "ARARANGUA"},
    {cidade: "BALSA NOVA", uf: "PR", agencia: "ARAUCARIA"},
    {cidade: "BANDEIRANTES", uf: "PR", agencia: "LONDRINA"},
    {cidade: "BARAO DO TRIUNFO", uf: "RS", agencia: "SAO LEOPOLDO"},
    {cidade: "BARBOSA FERRAZ", uf: "PR", agencia: "LONDRINA"},
    {cidade: "BARRA BONITA", uf: "SC", agencia: "SAO MIGUEL DO OESTE"},
    {cidade: "BARRA DO GUARITA", uf: "RS", agencia: "FREDERICO WESTPHALEN"},
    {cidade: "BARRA DO JACARE", uf: "PR", agencia: "LONDRINA"},
    {cidade: "BARRA DO RIO AZUL", uf: "RS", agencia: "ERECHIM"},
    {cidade: "BELA VISTA DO PARAISO", uf: "PR", agencia: "LONDRINA"},
    {cidade: "BENJAMIN CONSTANT DO SUL", uf: "RS", agencia: "ERECHIM"},
    {cidade: "BITURUNA", uf: "PR", agencia: "UNIAO DA VITORIA"},
    {cidade: "BOA VENTURA DE SAO ROQUE", uf: "PR", agencia: "LONDRINA"},
    {cidade: "BOA VISTA DA APARECIDA", uf: "PR", agencia: "LONDRINA"},
    {cidade: "BOA VISTA DO CADEADO", uf: "RS", agencia: "CRUZ ALTA"},
    {cidade: "BOA VISTA DO INCRA", uf: "RS", agencia: "CRUZ ALTA"},
    {cidade: "BOA VISTA DO SUL", uf: "RS", agencia: "ESTRELA"},
    {cidade: "BOCAINA DO SUL", uf: "PR", agencia: "LAGES"},
    {cidade: "BOCAIUVA DO SUL", uf: "PR", agencia: "CURITIBA"},
    {cidade: "BOM RETIRO", uf: "SC", agencia: "LAGES"},
    {cidade: "BOM SUCESSO DO SUL", uf: "PR", agencia: "PATO BRANCO"},
    {cidade: "BOQUEIRAO DO LEAO", uf: "RS", agencia: "SANTA CRUZ DO SUL"},
    {cidade: "BORRAZOPOLIS", uf: "PR", agencia: "MARINGA"},
    {cidade: "BOZANO", uf: "RS", agencia: "IJUI"},
    {cidade: "BRAGANEY", uf: "PR", agencia: "CASCAVEL AGENCIA"},
    {cidade: "BRASILIANDIA DO SUL", uf: "PR", agencia: "LONDRINA"},
    {cidade: "CAFEARA", uf: "PR", agencia: "LONDRINA"},
    {cidade: "CAMBARA DO SUL", uf: "RS", agencia: "GRAMADO"},
    {cidade: "CAMPINA DA LAGOA", uf: "PR", agencia: "LONDRINA"},
    {cidade: "CAMPINA DO SIMAO", uf: "PR", agencia: "GUARAPUAVA"},
    {cidade: "CAMPO BELO DO SUL", uf: "SC", agencia: "LAGES"},
    {cidade: "CAMPO BONITO", uf: "PR", agencia: "CASCAVEL AGENCIA"},
    {cidade: "CAMPO DO TENENTE", uf: "PR", agencia: "RIO NEGRO"},
    {cidade: "CAMPO MAGRO", uf: "PR", agencia: "CURITIBA"},
    {cidade: "CANDIDO DE ABREU", uf: "PR", agencia: "APUCARANA"},
    {cidade: "CANDOI", uf: "PR", agencia: "LONDRINA"},
    {cidade: "CAPAO ALTO", uf: "SC", agencia: "LAGES"},
    {cidade: "CAPAO BONITO DO SUL", uf: "RS", agencia: "LAGOA VERMELHA"},
    {cidade: "CAPAO DO CIPO", uf: "PR", agencia: "COLOMBO"},
    {cidade: "CAPITAO", uf: "RS", agencia: "ARROIO DO MEIO"},
    {cidade: "CARAA", uf: "RS", agencia: "SANTO ANTONIO DA PATRULHA"},
    {cidade: "CARLOPOLIS", uf: "PR", agencia: "LONDRINA"},
    {cidade: "CENTENARIO", uf: "RS", agencia: "ERECHIM"},
    {cidade: "CENTENARIO DO SUL", uf: "PR", agencia: "LONDRINA"},
    {cidade: "CERRITO", uf: "RS", agencia: "PELOTAS"},
    {cidade: "CERRO AZUL", uf: "PR", agencia: "COLOMBO"},
    {cidade: "CERRO GRANDE", uf: "RS", agencia: "FREDERICO WESTPHALEN"},
    {cidade: "CERRO GRANDE DO SUL", uf: "RS", agencia: "CAMAQUA"},
    {cidade: "CHAPADAO DO LAGEADO", uf: "SC", agencia: "RIO DO SUL"},
    {cidade: "CHARRUA", uf: "RS", agencia: "TAPEJARA"},
    {cidade: "CHUI", uf: "RS", agencia: "PELOTAS"},
    {cidade: "CHUVISCA", uf: "RS", agencia: "CAMAQUA"},
    {cidade: "CIDADE GAUCHA", uf: "PR", agencia: "CIANORTE"},
    {cidade: "COLORADO", uf: "PR", agencia: "LONDRINA"},
    {cidade: "CONGONHINHAS", uf: "PR", agencia: "LONDRINA"},
    {cidade: "CONSELHEIRO MANRINCK", uf: "PR", agencia: "LONDRINA"},
    {cidade: "COQUIEIRO BAIXO", uf: "RS", agencia: "LAJEADO"},
    {cidade: "COQUIEROS DO SUL", uf: "RS", agencia: "CARAZINHO"},
    {cidade: "CORONEL MARTINS", uf: "SC", agencia: "SAO LOURENCO DO OESTE"},
    {cidade: "CORONEL PILAR", uf: "RS", agencia: "GARIBALDI"},
    {cidade: "CORUMBATAI DO SUL", uf: "PR", agencia: "CAMPO MOURAO"},
    {cidade: "CRUZ MACHADO", uf: "PR", agencia: "UNIAO DA VITORIA"},
    {cidade: "CRUZALTENSE", uf: "RS", agencia: "ERECHIM"},
    {cidade: "CRUZEIRO DO SUL", uf: "PR", agencia: "LONDRINA"},
    {cidade: "CUNHATAI", uf: "SC", agencia: "PINHALZINHO"},
    {cidade: "CURIUVA", uf: "PR", agencia: "TELEMACO BORBA"},
    {cidade: "DERRUBADAS", uf: "RS", agencia: "TRES PASSOS"},
    {cidade: "DIAMANTE D'OESTE", uf: "PR", agencia: "MEDIANEIRA"},
    {cidade: "DIAMANTE DO NORTE", uf: "PR", agencia: "LONDRINA"},
    {cidade: "DIAMANTE DO SUL", uf: "PR", agencia: "LARANJEIRAS DO SUL"},
    {cidade: "DILERMANDO DE AGUIAR", uf: "RS", agencia: "SANTA MARIA"},
    {cidade: "DOM FELICIANO", uf: "RS", agencia: "CAMAQUA"},
    {cidade: "DOM PEDRO DE ALCANTRA", uf: "RS", agencia: "TORRES"},
    {cidade: "DONA EMMA", uf: "SC", agencia: "RIO DO SUL"},
    {cidade: "DOUTOR CAMARGO", uf: "PR", agencia: "LONDRINA"},
    {cidade: "DOUTOR PEDRINHO", uf: "SC", agencia: "TIMBO"},
    {cidade: "DOUTOR RICARDO", uf: "RS", agencia: "ARROIO DO MEIO"},
    {cidade: "DOUTOR ULYSSES", uf: "PR", agencia: "LONDRINA"},
    {cidade: "ENCRUZILHADA DO SUL", uf: "RS", agencia: "SANTA CRUZ DO SUL"},
    {cidade: "ENGENHEIRO BELTRAO", uf: "PR", agencia: "LONDRINA"},
    {cidade: "ENGENHO VELHO", uf: "RS", agencia: "SARANDI"},
    {cidade: "ENTRE RIOS", uf: "SC", agencia: "XAXIM"},
    {cidade: "ENTRE RIOS DO SUL", uf: "RS", agencia: "SARANDI"},
    {cidade: "ERVAL GRANDE", uf: "RS", agencia: "ERECHIM"},
    {cidade: "ESMERALDA", uf: "RS", agencia: "LAGOA VERMELHA"},
    {cidade: "ESTRELA VELHA", uf: "RS", agencia: "SOLEDADE"},
    {cidade: "EUGENIO DE CASTRO", uf: "RS", agencia: "IJUI"},
    {cidade: "FAXINALZINHO", uf: "RS", agencia: "ERECHIM"},
    {cidade: "FENIX", uf: "PR", agencia: "MARINGA"},
    {cidade: "FIGUEIRA", uf: "PR", agencia: "LONDRINA"},
    {cidade: "FLORESTA", uf: "PR", agencia: "MARINGA"},
    {cidade: "FLORESTOPOLIS", uf: "PR", agencia: "LONDRINA"},
    {cidade: "FLORIDA", uf: "PR", agencia: "LONDRINA"},
    {cidade: "FORMIGUEIRO", uf: "RS", agencia: "SANTA MARIA"},
    {cidade: "FOZ DO JORDAO", uf: "PR", agencia: "GUARAPUAVA"},
    {cidade: "GARRUCHOS", uf: "RS", agencia: "SAO LUIZ GONZAGA"},
]

function busca_cidade_ate_redesp(){
    var item_busca = document.getElementById('nome_cidade_redesp').value;
    document.getElementById('uf_redesp').value == ''
    document.getElementById('nome_agencia_redesp').value == ''

    for (const x in lista_cidades_redespacho) {
        if (Object.hasOwnProperty.call(lista_cidades_redespacho, x)) {
            const element = lista_cidades_redespacho[x];

            if (item_busca == element.cidade){
                document.getElementById('uf_redesp').value = element.uf;
                document.getElementById('nome_agencia_redesp').value = element.agencia;
            } 
            
        }
    }
}
